### ISSUE TITLE
User Story

### ISSUE THREAD

**Issue by DosBall** [DosBall/java-cell-auto-sim#4]
User Story:
    • Пользователь выбирает любое начальное состояние поля на свой вкус и благодаря нашему проекту наслаждается симулятором клеточных автоматов, работающий по определенному правилу
    • Пользователь выбирает количество шагов, которые выполнит наш симулятор
    • Пользователь может запустить "отладочный режим", дабы детальнее рассмотреть переходы из состояния в состояние

**Comment by nvamelichev** [comment]
User Story давно приняты, этот Issue предлагаю закрыть.
