### ISSUE TITLE
Замечания по CRC-карточкам

### ISSUE THREAD

**Issue by nvamelichev** [DosBall/java-cell-auto-sim#5]
- [x] CellScreen: Сейчас у класса прописанао тветственность "запуск окна с экраном на котором будет поле клеточного автомата" (и дальше в карточках есть ответственность типа "реагировать на щелчки мыши"). **Ответственность класса надо упростить!**
Заданием подразумевался **консольный** симулятор клеточных автоматов, в котором сложную графику и реакцию на щелчки мыши реализовать НЕ нужно (это технически возможно, но сильно вас затормозит &mdash; вы не успеете реализовать важную функциональность!)
Сам класс вполне можно оставить, он и в консольной версии приложения будет заниматься **выводом текущего состояния поля на экран** (и периодическим его обновлением).
- [x] Класс Field: пока это просто хранилище состояния клеток, это не класс - у него совсем нет поведения! Но, как мне кажется, поведение на самом деле есть - просто в CRC-карточках не прописано. Давайте подумаем:
  1. Может ли поле сообщать пользователям, в каком состоянии находятся клетки и изменять этот состояние? Ну да... И первое, что приходит на ум &mdash; методы "получить состояние ячейки"/"поменять состояние ячейки". Это &mdash; норм начало: для пользователей получается почти такой же интерфейс, как и обычный двумерный массив, но состояние ячеек может и вовсе не храниться в массиве, а, например, быть записанным в разреженную матрице, вычисляться динамически и т.д.
  2. Если добавить возможность оповещать CellScreen об изменении цвета клетки (паттерн "Наблюдатель") - то, по-моему, получится уже очень интересный вариант. Field будет регистрировать "слушателей", которых оповещают об изменениях цвета клеток (в нашем решении слушатель пока будет один - CellScreen). Как только кто-то вызывает у класса Field метод "поменяй цвет клетки", слушателей оповещают о том, что цвет клетки был изменён. И CellScreen НЕ придётся постоянно опрашивать состояние Field по таймеру - ему сразу сообщат об изменениях!
- [x] Класс Rules смешивает две ответственности: конфигурирует симулятор (выбор правила автомата, цвета клеток, размера поля) И реализует собственно правила клеточного автомата. Кажется, тут нужно два класса под каждую из этих ответственностей: класс "Конфигурация" с настройками, содержащий в себе (has-a) экземпляр класса "Правило клеточного автомата" (в зависимости от того, какое правило выбрал пользователь).
- [x] Класс ButtonChek, как я понимаю, реагирует на пользовательский ввод. Я бы переименовал его в "UserInput" или что-то вроде того.

**Comment by DosBall** [comment]
Спасибо за советы и замечания))

1) В нашем понимании автомат будет храниться в двумерном массиве в Field и изменение состояния отдельной клетки будет происходить в том же массиве. А уже потом весь изменённый массив будет отправляться в CellScreen и выводиться на экран. Это сделано чтобы не нагружать CellScreen изменением каждой отдельной клетки а сразу выводить всё изменённое поле на экран

2) Изменения будут происходить пошагово, регулярно (например раз в секунду) и сразу выводиться либо в консоль либо в отельное окно(над этим ещё работаем)

3) Реагирование на клик мышки убрали, оставили только возможность поставить автомат на "паузу" и сохранить текущее состояние автомата (скорее всего будем просто сохранять текстовый файл с двумерным массивом состояния клеток). Сохранение сделаем не просто так, его можно будет загрузить обратно и вывести на экран.

4) Rules разделили на два класса. В классе Config можно будет изменить правило автомата перед запуском. Класс ButtonChek переименовали :)

**Comment by nvamelichev** [comment]
CRC-карточки приняты :+1:
