### ISSUE TITLE
Замечания по UML-диаграммам

### ISSUE THREAD

**Issue by nvamelichev** [DosBall/java-cell-auto-sim#6]
- [x] На диаграмме классов перед именами всех методов поставлен знак "-". В нотации UML это означает "приватный метод", хотя все перечисленные на диаграмме методы на самом деле публичные. В UML публичные методы обозначаются значком "+"
- [x] Может быть, логику по завершению симуляции тоже переместить в класс UserInput? Приостановка симуляции уже там.
- [x] Что делает "Отправка конфигурации в Rules" в классе Config? Если настраивает размер поля, цвет клеток, интервал таймера и т.д. - то я не очень понимаю, зачем именно классу "правила клеточного автомата" знать про интервал таймера и цвет клеток, об этом наверное CellScreen должен знать. Про размер поля и начальную конфигурацию поля - немного другое дело, но, наверное, об этом тоже не сам класс Rules должен знать, а класс Field, скажем (а Rules просто берёт текущее состояние Field и трансформирует его в соответствии с правилами автомата.)
- [x] Есть ли между вашими классами отношения, кроме ассоциации ("использует"), например, композиция или агрегация? Если так, покажите их на диаграмме классов.
- [x] Есть ли между вашими классами отношения наследования или реализации интерфейса? Если есть, покажите их на диаграмме классов.
- [x] На диаграмме последовательности пользователя ("User") принято изображать в виде человечка (есть прямо такой значок в UML-нотации, в вашем UML-редакторе он должен быть :-))

**Comment by nvamelichev** [comment]
Стало заметно лучше! Нужно поправить совсем немного (но код уже можно и нужно писать :-)):
- [x] Сейчас на диаграмме классов нарисовано, как будто класс Files - наследник UserInput. (И много где ещё жирная стрелочка с белой заливкой). Скорее всего, вы имели в виду **ассоциацию** (отношение "как-то использует, но не содержит в качестве обязательной или опциональной составной части"). Ассоциация рисуется просто стрелочкой, типа такой: 
![просто стрелочка](https://www.plantuml.com/plantuml/png/SoWkIImgAStDuKhEIImkLeY0qf5S4GgwTa3A8JKl1IWD0000)
- [ ] Судя по диаграмме классов, класс Field (рабочее поле) содержит объект класса Rules (правила конечного автомата) в качестве неотъемлемой составной части (закрашенный ромбик - **композиция**). Это точно правильно? Точно ли правила конечного автомата - неотъемлемая часть рабочего поля с закрашенными клеточками? Если нет, то, возможно, правильное отношение здесь - это ассоциация ("использует"; изображается просто скучной стрелочкой, см. выше) или агрегация ("объединяется вместе со мной в целое для реализации конкретной задачи, но может жить и создаваться отдельно от меня"; изображается незакрашенным ромбиком). 
Пример про разницу между композицией, агрегацией и ассоциацией:
  - Класс `Автомобиль` может использовать класс `Домкрат` для реализации сценария "я чиню колесо", но домкрат - это не часть автомобиля, это просто инструмент, который можно использовать для починки колеса автомобиля. Это **ассоциация** - наиболее общий вид связи между классами.
  - С `водителем` и `0..* пассажирами` автомобиль состоит в отношении **агрегации**. Для выполнения самых важных функций автомобиля (ездить куда-то) ему нужно содержать `водителя` и, возможно, нескольких `пассажиров`. НО водитель неразрывно не связан с автомобилем: сегодня может быть один водитель, а завтра - другой (аналогично и с пассажирами). Поэтому **агрегация** сильнее ассоциации, но слабее композиции (см. ниже). **Агрегация** - это умеренный по силе вид связи "часть - целое" (A has-a B, "у A есть B").
  - `Автомобиль` содержит `Мотор` и `Колёса` как неотъемлемые части, жизненный цикл которых неразрывно связан с целым. Это **композиция**. Без мотора и колёс автомобиль фактически бесполезен, а в нашей простой объектной модели из примера - и вовсе существовать не может (и при создании автомобиля мы будем автоматически создавать мотор и колёса). **Композиция** - это самый сильный вид связи "часть-целое" (A has-a B, "A содержит B как неотъемлемую часть").

**Comment by Iliyas-Kalkamanov** [comment]
Да, там где была белая стрелочка действительно должна была быть ассоциация. В конструкторе оказывается это указывается как просто соединение, немного напутал в процессе и принял эту стрелку за нужную. 
Класс Rules является обязательной частью Field'а ведь в процессе выполнения задачи они неразрывно связаны. Возможно стоит аналогично отобразить связь межу Field и CellScreen как композицию.

Честно говоря не совсем понимаю разницу между водителем и колесами и двигателями, ведь они тоже заменяемые

**Comment by nvamelichev** [comment]
Я сейчас ещё подумал... И кажется, что класс, управляющий логикой автомата по изменению клеточек на поле (Rules) - не является вообще **никакой** частью поля из клеточек, которое он меняет. Между ними, скорее, ассоциация: "правило автомата использует поле, чтобы узнать, какие состояния у клеток и задать новые состояния клеток".

Пример про колёса и двигатель получился не очень удачный, в реальной жизни в автомобиле можно примерно что угодно заменить :-)

Разница между отношениями классов в том, как устроена работа целого с частью:
- При **композиции**, часть появляется в момент появления целого (например, создаётся в конструкторе класса), и при после уничтожения целого &mdash; более не существует. Часть невозможно использовать в отрыве от целого, даже пока целое существует.
- При **агрегации**, часть создаётся отдельно от целого и дальше каким-то образом к нему присоединяется для выполнения его обязанностей (например, проставляется значение в поле, или вызывается метод). При агрегации, часть иногда может быть использована вообще без целого.
- При **ассоциации**, объекты создаются отдельно, но **могут** как-то воспользоваться услугами друг друга. В коде это может быть выражено и как то, что объект A передаётся в метод B; и как то, что объект A является полем B, и B вызывает методы A &mdash; просто потому что это удобно.
Например, если у вас есть класс-фасад, предоставляющий простой интерфейс для взаимодействия с десятью компонентами вашей системы - то полей в классе вполне может быть восемь, но это не составные части класса, а просто его "друзья", так сказать &mdash; помогающие выполнять классу свои обязанности.

**Comment by nvamelichev** [comment]
В остальном (кроме отношения между Rules и Field) замечаний по UML-диаграммам больше нет :-)
